"""Add versioning tables

Revision ID: 876ada1921e0
Revises: 30ba5fbe0aea
Create Date: 2025-07-07 11:05:38.237155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876ada1921e0'
down_revision: Union[str, None] = '30ba5fbe0aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
